import { VerificationCase, WorkflowDefinition, ExtractedDocumentData } from './types';

export const SPECIMEN_DOCUMENTS: {
  validPassport: ExtractedDocumentData;
  validNationalId: ExtractedDocumentData;
  fraudulentDocument: ExtractedDocumentData;
} = {
  validPassport: {
    documentType: 'PASSPORT',
    country: 'Utopia',
    countryCode: 'UTO',
    fullName: 'ELEANOR JANE VANCE',
    givenNames: 'ELEANOR JANE',
    surname: 'VANCE',
    documentNumber: 'UT001234567',
    dateOfBirth: '12 APR 1986',
    expiryDate: '14 JAN 2034',
    issueDate: '15 JAN 2024',
    nationality: 'UTOPIAN',
    gender: 'F',
    mrzRaw: 'P<UTO<<VANCE<<ELEANOR<JANE<<<<<<<<<<<<<<<<<<<\nUT001234567UT08604128F3401140<<<<<<<<<<<<<<00',
    mrzValid: true,
    barcodeValid: true,
    chipAuthentication: 'OK',
    securityFeatures: {
      guillochePattern: true,
      hologramCheck: true,
      tamperDetected: false,
      uvOrIRValid: true,
    },
  },
  validNationalId: {
    documentType: 'NATIONAL_ID',
    country: 'Federal Republic',
    countryCode: 'FED',
    fullName: 'MARCUS ALEXANDER CHEN',
    givenNames: 'MARCUS ALEXANDER',
    surname: 'CHEN',
    documentNumber: 'FED-99382104',
    dateOfBirth: '24 NOV 1991',
    expiryDate: '24 NOV 2031',
    issueDate: '01 DEC 2021',
    nationality: 'FEDERAL',
    gender: 'M',
    mrzRaw: 'IDFED993821046<<<<<<<<<<<<<<<\n9111245M3111242FED<<<<<<<<<<<4\nCHEN<<MARCUS<ALEXANDER<<<<<<<',
    mrzValid: true,
    barcodeValid: true,
    chipAuthentication: 'OK',
    securityFeatures: {
      guillochePattern: true,
      hologramCheck: true,
      tamperDetected: false,
      uvOrIRValid: true,
    },
  },
  fraudulentDocument: {
    documentType: 'DRIVING_LICENSE',
    country: 'United States',
    countryCode: 'USA',
    fullName: 'RICHARD J. DOE',
    givenNames: 'RICHARD J.',
    surname: 'DOE',
    documentNumber: 'DL-48192019A',
    dateOfBirth: '05 MAY 1978',
    expiryDate: '05 MAY 2028',
    issueDate: '01 JAN 2018',
    nationality: 'USA',
    gender: 'M',
    mrzRaw: undefined,
    mrzValid: false,
    barcodeValid: false,
    chipAuthentication: 'FAILED',
    securityFeatures: {
      guillochePattern: false,
      hologramCheck: false,
      tamperDetected: true,
      uvOrIRValid: false,
    },
  },
};

export const INITIAL_VERIFICATION_CASES: VerificationCase[] = [
  {
    id: 'VR-829182',
    customerReference: 'cust_live_89104',
    applicantName: 'Marcus Alexander Chen',
    country: 'Germany / Federal',
    documentType: 'NATIONAL_ID',
    documentNumber: 'FED-99382104',
    createdAt: '2 mins ago',
    status: 'VIDEO_KYC_WAITING',
    riskLevel: 'HIGH',
    riskScore: 76,
    faceMatchScore: 0.94,
    livenessScore: 0.96,
    assignedAgent: 'Agent Sarah Jenkins',
    waitTimeSeconds: 45,
    documentData: SPECIMEN_DOCUMENTS.validNationalId,
    biometrics: {
      faceDetected: true,
      faceMatchScore: 0.94,
      livenessScore: 0.96,
      livenessMode: 'ACTIVE',
      presentationAttackDetected: false,
      lightingQuality: 'GOOD',
      headPose: { pitch: -2, yaw: 4, roll: 0 },
    },
    riskEvaluation: {
      riskScore: 76,
      riskLevel: 'HIGH',
      recommendation: 'VIDEO_KYC',
      signals: {
        documentAuthenticity: 96,
        biometricMatch: 94,
        livenessIntegrity: 96,
        deviceIntegrity: 45, // Emulator/proxy detected
        networkRisk: 68, // Datacenter/Tor IP
        amlPepMatch: false,
        behavioralAnomalies: 42,
      },
      reasons: [
        'Anomalous connection from commercial proxy',
        'Device fingerprint mismatch with previous session',
        'Requires Live Video KYC per Rule #4 (High-Risk Threshold > 70)',
      ],
    },
    actionsCompleted: ['LOOK_LEFT', 'LOOK_RIGHT', 'BLINK'],
    auditLogs: [
      { id: '1', timestamp: '12:15:02', actor: 'SYSTEM', action: 'SESSION_CREATED', detail: 'Verification token generated via API' },
      { id: '2', timestamp: '12:15:20', actor: 'USER', action: 'DOC_CAPTURED', detail: 'National ID submitted and parsed' },
      { id: '3', timestamp: '12:15:45', actor: 'SYSTEM', action: 'MRZ_VALIDATED', detail: 'ICAO checksums valid' },
      { id: '4', timestamp: '12:16:10', actor: 'SYSTEM', action: 'ACTIVE_LIVENESS_PASSED', detail: 'Blink & head pose verified' },
      { id: '5', timestamp: '12:16:15', actor: 'SYSTEM', action: 'RISK_TRIGGERED', detail: 'Score 76 > 70. Escalated to Video KYC Queue' },
    ],
  },
  {
    id: 'VR-829183',
    customerReference: 'cust_live_89105',
    applicantName: 'Eleanor Jane Vance',
    country: 'United Kingdom',
    documentType: 'PASSPORT',
    documentNumber: 'UT001234567',
    createdAt: '8 mins ago',
    status: 'APPROVED',
    riskLevel: 'LOW',
    riskScore: 12,
    faceMatchScore: 0.98,
    livenessScore: 0.99,
    assignedAgent: 'System Automated',
    documentData: SPECIMEN_DOCUMENTS.validPassport,
    biometrics: {
      faceDetected: true,
      faceMatchScore: 0.98,
      livenessScore: 0.99,
      livenessMode: 'PASSIVE',
      presentationAttackDetected: false,
      lightingQuality: 'GOOD',
      headPose: { pitch: 0, yaw: 1, roll: 0 },
    },
    riskEvaluation: {
      riskScore: 12,
      riskLevel: 'LOW',
      recommendation: 'PASS',
      signals: {
        documentAuthenticity: 100,
        biometricMatch: 98,
        livenessIntegrity: 99,
        deviceIntegrity: 98,
        networkRisk: 10,
        amlPepMatch: false,
        behavioralAnomalies: 5,
      },
      reasons: ['All biometric and forensic authenticity checks passed seamlessly'],
    },
    actionsCompleted: ['TURN_LEFT', 'SMILE', 'BLINK', 'TILT_ID'],
    auditLogs: [
      { id: '1', timestamp: '12:08:12', actor: 'SYSTEM', action: 'SESSION_CREATED', detail: 'Automated Tier 1 KYC initiated' },
      { id: '2', timestamp: '12:08:34', actor: 'USER', action: 'DOC_CAPTURED', detail: 'ePassport scanned with valid RFID chip' },
      { id: '3', timestamp: '12:08:50', actor: 'SYSTEM', action: 'BIOMETRICS_MATCHED', detail: '1:1 Match 98.4% with Live Selfie' },
      { id: '4', timestamp: '12:09:00', actor: 'SYSTEM', action: 'DECISION_APPROVED', detail: 'Low risk score 12. Automated approval granted' },
    ],
  },
  {
    id: 'VR-829184',
    customerReference: 'cust_live_89106',
    applicantName: 'Sarah Al-Mansoor',
    country: 'United Arab Emirates',
    documentType: 'PASSPORT',
    documentNumber: 'AE-77291039',
    createdAt: '14 mins ago',
    status: 'VIDEO_KYC_WAITING',
    riskLevel: 'MEDIUM',
    riskScore: 54,
    faceMatchScore: 0.89,
    livenessScore: 0.93,
    assignedAgent: 'Agent David Mercer',
    waitTimeSeconds: 80,
    biometrics: {
      faceDetected: true,
      faceMatchScore: 0.89,
      livenessScore: 0.93,
      livenessMode: 'ACTIVE',
      presentationAttackDetected: false,
      lightingQuality: 'POOR',
      headPose: { pitch: 1, yaw: -3, roll: 2 },
    },
    riskEvaluation: {
      riskScore: 54,
      riskLevel: 'MEDIUM',
      recommendation: 'VIDEO_KYC',
      signals: {
        documentAuthenticity: 91,
        biometricMatch: 89,
        livenessIntegrity: 93,
        deviceIntegrity: 82,
        networkRisk: 40,
        amlPepMatch: false,
        behavioralAnomalies: 30,
      },
      reasons: ['Sub-optimal lighting during selfie capture', 'Manual Video KYC requested to confirm passport portrait match'],
    },
    actionsCompleted: ['TURN_LEFT', 'BLINK'],
    auditLogs: [
      { id: '1', timestamp: '12:02:11', actor: 'SYSTEM', action: 'SESSION_CREATED', detail: 'High-value account verification' },
      { id: '2', timestamp: '12:02:50', actor: 'USER', action: 'DOC_CAPTURED', detail: 'Passport visual zone verified' },
      { id: '3', timestamp: '12:03:20', actor: 'SYSTEM', action: 'ESCALATED', detail: 'Lighting warning. Escalated to Video KYC queue' },
    ],
  },
  {
    id: 'VR-829185',
    customerReference: 'cust_live_89107',
    applicantName: 'Richard J. Doe (Altered)',
    country: 'United States',
    documentType: 'DRIVING_LICENSE',
    documentNumber: 'DL-48192019A',
    createdAt: '22 mins ago',
    status: 'REJECTED',
    riskLevel: 'HIGH',
    riskScore: 98,
    faceMatchScore: 0.42,
    livenessScore: 0.15,
    assignedAgent: 'System Automated',
    documentData: SPECIMEN_DOCUMENTS.fraudulentDocument,
    biometrics: {
      faceDetected: true,
      faceMatchScore: 0.42,
      livenessScore: 0.15,
      livenessMode: 'PASSIVE',
      presentationAttackDetected: true,
      attackType: 'PRINT_ATTACK',
      lightingQuality: 'GOOD',
      headPose: { pitch: 0, yaw: 0, roll: 0 },
    },
    riskEvaluation: {
      riskScore: 98,
      riskLevel: 'HIGH',
      recommendation: 'REJECT',
      signals: {
        documentAuthenticity: 12,
        biometricMatch: 42,
        livenessIntegrity: 15,
        deviceIntegrity: 80,
        networkRisk: 90,
        amlPepMatch: false,
        behavioralAnomalies: 95,
      },
      reasons: [
        'Document tampering detected in expiry date zone',
        'Presentation attack detected: paper printout artifact on camera',
        'Biometric mismatch between ID card photo and captured selfie',
      ],
    },
    actionsCompleted: [],
    auditLogs: [
      { id: '1', timestamp: '11:55:01', actor: 'SYSTEM', action: 'SESSION_CREATED', detail: 'Verification attempt initiated' },
      { id: '2', timestamp: '11:55:18', actor: 'SYSTEM', action: 'TAMPER_FLAGGED', detail: 'Guilloche pattern interrupted near DOB' },
      { id: '3', timestamp: '11:55:30', actor: 'SYSTEM', action: 'SPOOF_DETECTED', detail: 'ISO 30107-3 PAD level 2 print attack confirmed' },
      { id: '4', timestamp: '11:55:32', actor: 'SYSTEM', action: 'DECISION_REJECTED', detail: 'Critical fraud signal threshold breached' },
    ],
  },
  {
    id: 'VR-829186',
    customerReference: 'cust_live_89108',
    applicantName: 'Julian Tanaka',
    country: 'Japan',
    documentType: 'PASSPORT',
    documentNumber: 'JP-92817263',
    createdAt: '35 mins ago',
    status: 'APPROVED',
    riskLevel: 'LOW',
    riskScore: 8,
    faceMatchScore: 0.97,
    livenessScore: 0.99,
    assignedAgent: 'System Automated',
    biometrics: {
      faceDetected: true,
      faceMatchScore: 0.97,
      livenessScore: 0.99,
      livenessMode: 'PASSIVE',
      presentationAttackDetected: false,
      lightingQuality: 'GOOD',
      headPose: { pitch: 0, yaw: 0, roll: 0 },
    },
    riskEvaluation: {
      riskScore: 8,
      riskLevel: 'LOW',
      recommendation: 'PASS',
      signals: {
        documentAuthenticity: 100,
        biometricMatch: 97,
        livenessIntegrity: 99,
        deviceIntegrity: 99,
        networkRisk: 5,
        amlPepMatch: false,
        behavioralAnomalies: 3,
      },
      reasons: ['Flawless ePassport validation and genuine active biometric match'],
    },
    actionsCompleted: ['TURN_LEFT', 'TURN_RIGHT', 'SMILE'],
    auditLogs: [
      { id: '1', timestamp: '11:41:10', actor: 'SYSTEM', action: 'SESSION_CREATED', detail: 'Japan onboarding pipeline' },
      { id: '2', timestamp: '11:41:40', actor: 'USER', action: 'DOC_CAPTURED', detail: 'Japanese ePassport verified with NFC chip' },
      { id: '3', timestamp: '11:42:01', actor: 'SYSTEM', action: 'DECISION_APPROVED', detail: 'Risk score 8. Clean verification' },
    ],
  },
];

export const MOCK_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: 'wf_fintech_standard',
    name: 'Standard FinTech & Neobank KYC',
    description: 'Instant document OCR, biometric face match, passive liveness, and automated risk scoring with Video KYC fallback for risk > 70.',
    isDefault: true,
    lastModified: 'Today, 10:14 AM',
    nodes: [
      { id: 'node_1', name: 'Capture Session Trigger', type: 'TRIGGER', category: 'CAPTURE', status: 'ACTIVE', config: { channel: 'WEB_MOBILE' } },
      { id: 'node_2', name: 'Document Forensics & OCR', type: 'DOC_OCR', category: 'CAPTURE', status: 'ACTIVE', config: { autoRotate: true, blurThreshold: 0.8 } },
      { id: 'node_3', name: 'ICAO 9303 MRZ Check', type: 'MRZ_CHECK', category: 'CAPTURE', status: 'ACTIVE', config: { strictChecksums: true } },
      { id: 'node_4', name: 'Passive Liveness (ISO 30107-3)', type: 'PASSIVE_LIVENESS', category: 'BIOMETRICS', status: 'ACTIVE', config: { threshold: 0.95 } },
      { id: 'node_5', name: 'Dynamic Action Challenge', type: 'ACTION_CHALLENGE', category: 'BIOMETRICS', status: 'ACTIVE', config: { challengesCount: 3, randomize: true } },
      { id: 'node_6', name: '1:1 Biometric Face Match', type: 'FACE_MATCH', category: 'BIOMETRICS', status: 'ACTIVE', config: { similarityThreshold: 0.85 } },
      { id: 'node_7', name: 'AML & PEP Sanctions Screening', type: 'AML_SCREENING', category: 'RISK', status: 'ACTIVE', config: { provider: 'GLOBAL_WATCHLIST_v2' } },
      { id: 'node_8', name: 'Risk Rules Decision Engine', type: 'RISK_ENGINE', category: 'RISK', status: 'ACTIVE', config: { autoApproveUnder: 40, escalateOver: 70 } },
      { id: 'node_9', name: 'Live Video KYC Escalation', type: 'VIDEO_KYC', category: 'HUMAN_REVIEW', status: 'ACTIVE', config: { queuePriority: 'HIGH', timeoutMinutes: 5 } },
      { id: 'node_10', name: 'Final Decision & Signed Webhook', type: 'DECISION', category: 'OUTPUT', status: 'ACTIVE', config: { signPayload: true } },
    ],
  },
  {
    id: 'wf_crypto_high_risk',
    name: 'High-Risk Tier 3 Crypto / Large Transfers',
    description: 'Enforces mandatory active head turn challenges, NFC biometric chip extraction, deepfake defense, and human Video KYC confirmation.',
    isDefault: false,
    lastModified: 'Yesterday, 4:30 PM',
    nodes: [
      { id: 'node_c1', name: 'High-Value Trigger', type: 'TRIGGER', category: 'CAPTURE', status: 'ACTIVE', config: { minLimitUSD: 10000 } },
      { id: 'node_c2', name: 'ePassport & NFC Chip Reader', type: 'NFC_CHIP', category: 'CAPTURE', status: 'ACTIVE', config: { requireBiometricChip: true } },
      { id: 'node_c3', name: 'Deepfake & Virtual Cam Detector', type: 'PASSIVE_LIVENESS', category: 'BIOMETRICS', status: 'ACTIVE', config: { checkVideoInjection: true } },
      { id: 'node_c4', name: '4-Stage Action Verification', type: 'ACTION_CHALLENGE', category: 'BIOMETRICS', status: 'ACTIVE', config: { includeDocTilt: true } },
      { id: 'node_c5', name: 'Live Video KYC Inspector Session', type: 'VIDEO_KYC', category: 'HUMAN_REVIEW', status: 'ACTIVE', config: { recordingEncrypted: true, minDurationSec: 60 } },
      { id: 'node_c6', name: 'Compliance Sign-off', type: 'DECISION', category: 'OUTPUT', status: 'ACTIVE', config: { requireInspectorSignature: true } },
    ],
  },
];
